project_id = "csylbxuiukwhpybuhizr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.chat-completion]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
